<?php

/**
 * PluginMovieTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMovieTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMovieTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMovie');
    }
}