<?php

/**
 * PluginMoviePlayRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMoviePlayRankTable extends Doctrine_Table
{
  public function updateRank(Movie $movie, Member $member = null)
  {
    if ($movie->Member->id === $member->id || null === $member)
    {
      return false;
    }

    if ($rank = $this->findOneByMemberIdAndMovieId($member->id, $movie->id))
    {
      return false;
    }

    $conn = $this->getConnection();
    try
    {
      $conn->beginTransaction();

      $rank = new MoviePlayRank();
      $rank->setMember($member);
      $rank->setMovie($movie);
      $rank->save($conn);
      $movie->playTotal();
      $movie->save($conn);

      $conn->commit();
    }
    catch(Exception $e)
    {
      $conn->rollback();
      // do nothing
      sfContext::getInstance()->getLogger()->err($e->getTraceAsString());

      return false;
    }

    return true;
  }

  /**
   * Returns an instance of this class.
   *
   * @return object PluginMoviePlayRankTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginMoviePlayRank');
  }
}
