<?php

/**
 * PluginMovieCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginMovieCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginMovieCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginMovieComment');
    }
}